AWSTemplateFormatVersion: '2010-09-09'
Description: 'The containers and service configuration for CiviForm.'
Parameters:
  Environment:
    Type: String
    AllowedValues: ['prod']
    Description: 'Staging or prod environment'
  S3TaskRole:
    Description: The task role for the containers.
    Type: String
  DBAddress:
    Description: The address at which the database can be reached.
    Type: String
  DBPort:
    Description: The port on which the database can be reached.
    Type: String
  LBTargetName:
    Description: The load balancer target group to add new containers to.
    Type: String
  ContainerSecurityGroup:
    Description: The security group to use for the containers.
    Type: String
  PrivateSubnet1:
    Description: The private subnets to add the database to.
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Description: The private subnet to add the database to.
    Type: AWS::EC2::Subnet::Id
  S3BucketName:
    Description: S3 bucket name for file storage.
    Type: String
  DBUsername:
    NoEcho: 'true'
    Description: Username for database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password for database access
    Type: String
  SecretKey:
    NoEcho: 'true'
    Description: Secret key for Play application
    Type: String
  DomainName:
    Description: The domain name to use as the base URL.
    Type: String
  MeasurementId:
    Description: The Google Analytics measurement ID.
    Type: String
Resources:
  ecscluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['-', [!Ref Environment, 'civiform-fargate-cluster']]
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
  ecsservice:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'ecscluster'
      DesiredCount: 2
      TaskDefinition: !Ref 'ecstaskdef'
      LoadBalancers:
        - ContainerName: !Join ['-', [!Ref Environment, 'civiform-container']]
          ContainerPort: 9000
          TargetGroupArn: !Ref 'LBTargetName'
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref 'ContainerSecurityGroup'
          Subnets:
            - !Ref 'PrivateSubnet1'
            - !Ref 'PrivateSubnet2'
  loggroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['.', [!Ref Environment, 'civiform.lg']]
      RetentionInDays: 90
  ecstaskdef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !Ref S3TaskRole
      ExecutionRoleArn: arn:aws:iam::405662711265:role/ecs-task-role
      NetworkMode: awsvpc
      Cpu: 1024
      Memory: 8192
      ContainerDefinitions:
        - Name: !Join ['-', [!Ref Environment, 'civiform-container']]
          Image: 'public.ecr.aws/t1q6b4h2/universal-application-tool:prod'
          Environment:
            - Name: DB_JDBC_STRING
              Value: !Join
                - ''
                - - jdbc:postgresql://
                  - !Ref 'DBAddress'
                  - ':'
                  - !Ref 'DBPort'
                  - /postgres
            - Name: DB_USERNAME
              Value: !Ref 'DBUsername'
            - Name: DB_PASSWORD
              Value: !Sub '{{resolve:secretsmanager:${DBPassword}}}'
            - Name: SECRET_KEY
              Value: !Sub '{{resolve:secretsmanager:${SecretKey}}}'
            - Name: AWS_REGION
              Value: !Sub '${AWS::Region}'
            - Name: SENDER_EMAIL_ADDRESS
              Value: 'civiform-notification@seattle.gov'
            - Name: AWS_S3_BUCKET_NAME
              Value: !Ref 'S3BucketName'
            - Name: IDCS_CLIENT_ID
              Value: !Sub '{{resolve:secretsmanager:${Environment}-oidc-secrets:SecretString:IDCS_CLIENT_ID}}'
            - Name: IDCS_SECRET
              Value: !Sub '{{resolve:secretsmanager:${Environment}-oidc-secrets:SecretString:IDCS_SECRET}}'
            - Name: IDCS_DISCOVERY_URI
              Value: 'https://idcs-3359adb31e35415e8c1729c5c8098c6d.identity.oraclecloud.com/.well-known/openid-configuration'
            - Name: ADFS_CLIENT_ID
              Value: !Sub '{{resolve:secretsmanager:${Environment}-oidc-secrets:SecretString:ADFS_CLIENT_ID}}'
            - Name: ADFS_SECRET
              Value: !Sub '{{resolve:secretsmanager:${Environment}-oidc-secrets:SecretString:ADFS_SECRET}}'
            - Name: ADFS_DISCOVERY_URI
              Value: 'https://login.microsoftonline.com/78e61e45-6beb-4009-8f99-359d8b54f41b/v2.0/.well-known/openid-configuration'
            - Name: APPLICANT_REGISTER_URI
              Value: 'https://login.seattle.gov/#/registration?appName=CiviForm'
            - Name: ADFS_ADMIN_GROUP
              Value: 'f8c8e6c8-a5d7-4476-91bd-7f1691d16625'
            - Name: WHITELABEL_CIVIC_ENTITY_SHORT_NAME
              Value: 'Seattle'
            - Name: WHITELABEL_CIVIC_ENTITY_FULL_NAME
              Value: 'City of Seattle'
            - Name: BASE_URL
              Value: !Sub 'https://${DomainName}'
            - Name: MEASUREMENT_ID
              Value: !Sub '${MeasurementId}'
            - Name: CIVIFORM_API_SECRET_SALT
              Value: !Sub '{{resolve:secretsmanager:${Environment}-api-secret-salt:SecretString:CIVIFORM_API_SECRET_SALT}}'
            - Name: DATABASE_APPLY_DESTRUCTIVE_CHANGES
              Value: 'true'
            - Name: CIVIFORM_API_KEYS_BAN_GLOBAL_SUBNET
              Value: 'true'
            - Name: FEATURE_FLAG_OVERRIDES_ENABLED
              Value: 'false'
            - Name: APPLICANT_OIDC_PROVIDER_LOGOUT
              Value: 'true'
            - Name: APPLICANT_OIDC_OVERRIDE_LOGOUT_URL
              Value: 'https://login.seattle.gov/#/logout?appName=CIVIFORM'
            - Name: APPLICANT_OIDC_POST_LOGOUT_REDIRECT_PARAM
              Value: ''
            - Name: ALLOW_CIVIFORM_ADMIN_ACCESS_PROGRAMS
              Value: 'true'
            - Name: STAGING_PROGRAM_ADMIN_NOTIFICATION_MAILING_LIST
              Value: 'civiForm.staging@seattle.gov'
            - Name: STAGING_TI_NOTIFICATION_MAILING_LIST
              Value: 'civiForm.staging@seattle.gov'
            - Name: STAGING_APPLICANT_NOTIFICATION_MAILING_LIST
              Value: 'civiForm.staging@seattle.gov'
            - Name: STAGING_HOSTNAME
              Value: 'civiformstage.seattle.gov'
            - Name: ESRI_ADDRESS_CORRECTION_ENABLED
              Value: 'true'
            - Name: ESRI_FIND_ADDRESS_CANDIDATES_URL
              Value: 'https://gisdata.seattle.gov/cosgis/rest/services/locators/AddressPoints/GeocodeServer/findAddressCandidates'
            - Name: ESRI_ADDRESS_SERVICE_AREA_VALIDATION_ENABLED
              Value: 'true'
            - Name: ESRI_ADDRESS_SERVICE_AREA_VALIDATION_LABELS.0
              Value: 'Seattle'
            - Name: ESRI_ADDRESS_SERVICE_AREA_VALIDATION_IDS.0
              Value: 'Seattle'
            - Name: ESRI_ADDRESS_SERVICE_AREA_VALIDATION_URLS.0
              Value: 'https://gisdata.seattle.gov/server/rest/services/COS/Seattle_City_Limits/MapServer/1/query'
            - Name: ESRI_ADDRESS_SERVICE_AREA_VALIDATION_ATTRIBUTES.0
              Value: 'CITYNAME'
            - Name: PROGRAM_READ_ONLY_VIEW_ENABLED
              Value: 'true'
            - Name: APPLICATION_EXPORTABLE
              Value: 'true'
            - Name: BYPASS_LOGIN_LANGUAGE_SCREENS
              Value: 'true'
            - Name: SUPPORT_EMAIL_ADDRESS
              Value: CiviForm@seattle.gov
            - Name: COMMON_INTAKE_MORE_RESOURCES_LINK_TEXT
              Value: Affordable Seattle
            - Name: COMMON_INTAKE_MORE_RESOURCES_LINK_HREF
              Value: https://www.affordableseattle.org
            - Name: WHITELABEL_LOGO_WITH_NAME_URL
              Value: https://raw.githubusercontent.com/seattle-civiform/civiform-deploy-tf/main/logos/civiform-long-logo.png
            - Name: CIVIC_ENTITY_SMALL_LOGO_URL
              Value: https://raw.githubusercontent.com/seattle-civiform/civiform-deploy-tf/main/logos/civiform-small-logo.png
            - Name: FAVICON_URL
              Value: https://seattle.gov/favicon.ico
            - Name: APPLICANT_PORTAL_NAME
              Value: Seattle
            - Name: ADFS_ADDITIONAL_SCOPES
              Value: ''
            - Name: AD_GROUPS_ATTRIBUTE_NAME
              Value: 'groups'
            - Name: ADMIN_SETTINGS_PANEL_ENABLED
              Value: 'true'
            - Name: STAGING_ADD_NOINDEX_META_TAG
              Value: 'false'
            - Name: CIVIFORM_SUPPORTED_LANGUAGES.0
              Value: 'en-US'
            - Name: CIVIFORM_SUPPORTED_LANGUAGES.1
              Value: 'am'
            - Name: CIVIFORM_SUPPORTED_LANGUAGES.2
              Value: 'zh-TW'
            - Name: CIVIFORM_SUPPORTED_LANGUAGES.3
              Value: 'ko'
            - Name: CIVIFORM_SUPPORTED_LANGUAGES.4
              Value: 'so'
            - Name: CIVIFORM_SUPPORTED_LANGUAGES.5
              Value: 'es-US'
            - Name: CIVIFORM_SUPPORTED_LANGUAGES.6
              Value: 'tl'
            - Name: CIVIFORM_SUPPORTED_LANGUAGES.7
              Value: 'vi'
            - Name: CLIENT_IP_TYPE
              Value: 'FORWARDED'
            - Name: VERSION_CACHE_ENABLED
              Value: 'true'
            - Name: PROGRAM_CACHE_ENABLED
              Value: 'true'
            - Name: QUESTION_CACHE_ENABLED
              Value: 'true'
          Cpu: 1024
          Memory: 8192
          PortMappings:
            - ContainerPort: '9000'
              HostPort: '9000'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'loggroup'
              awslogs-region: !Sub '${AWS::Region}'
              awslogs-stream-prefix: civiformsrv
          Essential: true
  autoscalingtarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 2
      MaxCapacity: 5
      ResourceId: !Join ['/', [service, !Ref ecscluster, !GetAtt ecsservice.Name]]
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: arn:aws:iam::405662711265:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
  autoscalingpolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: CiviFormAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref autoscalingtarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
        # Keep things at or lower than 75% CPU utilization
        TargetValue: 75
Outputs:
  ECSService:
    Description: The ARN of the service.
    Value: !Ref 'ecsservice'
    Export:
      Name: !Sub '${AWS::StackName}-ECSService'
  ECSCluster:
    Description: The ARN of the cluster.
    Value: !GetAtt 'ecscluster.Arn'
    Export:
      Name: !Sub '${AWS::StackName}-ECSCluster'
