
name: Run Probers Only

on:
  workflow_dispatch: {}

#permissions: read-all

# Two probers running at once can break each other.
concurrency:
  group: stagingenvironment
  cancel-in-progress: true

jobs:
  run_prober:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Prober tests
        env:
          TEST_USER_LOGIN: ${{ secrets.TEST_USER_LOGIN }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 70
          max_attempts: 1
          retry_wait_seconds: 30
          command: bin/run-prober 1
          
      - name: Upload test videos on failure
        uses: actions/upload-artifact@v3
        with:
          name: tests videos
          path: browser-test/tmp
        if: failure()
