name: Slack Notification Tester

on:
  workflow_dispatch: {}

permissions: read-all

jobs:
  run_prober:
    runs-on: ubuntu-latest
    steps:
      - name: Try to fail
        run: exit 1
      
      - name: Notify Slack Complete
        if: always()
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id:  'C03UXPUEXU4'
          slack-message: "Test Message from Seattle Staging Deploy:  ${{ job.status }} ${{ env.ICON }} ${{ env.URL }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          ICON: ${{fromJSON('[":no_entry:", ":white_check_mark:"]')[job.status == 'success']}}
          URL: ${{fromJSON('["${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", ":white_check_mark:"]')[job.status == 'success']}}
